-- ============================================================
--  AgriKA-GIS — seed / reference data
--  Run AFTER schema.sql.
--
--  NOTE: user accounts are NOT created here. Password hashes must
--  be generated by the Flask app's hashing library so login can
--  verify them. Use backend/scripts/create_user.py for that.
-- ============================================================

-- ---- Roles (the three portal roles) ----
INSERT INTO roles (role_name) VALUES
    ('administrator'),
    ('agriculturist'),
    ('rice_technician');

-- ---- Municipalities / cities of Laguna (rice-producing subset) ----
INSERT INTO municipalities (municipality_name) VALUES
    ('Calamba'),
    ('Cabuyao'),
    ('Santa Rosa'),
    ('Biñan'),
    ('San Pablo'),
    ('Los Baños'),
    ('Bay'),
    ('Pila'),
    ('Calauan'),
    ('Victoria');

-- ---- Seasons (Wet / Dry across recent years) ----
INSERT INTO seasons (season_type, year) VALUES
    ('Dry', 2023),
    ('Wet', 2023),
    ('Dry', 2024),
    ('Wet', 2024);

-- ---- A few sample barangays (boundary_geometry left NULL for now;
--       real polygons get imported later from a shapefile/GeoJSON) ----
INSERT INTO barangays (barangay_name, municipality_id) VALUES
    ('San Isidro',     (SELECT municipality_id FROM municipalities WHERE municipality_name = 'Calamba')),
    ('Bucal',          (SELECT municipality_id FROM municipalities WHERE municipality_name = 'Calamba')),
    ('Mamatid',        (SELECT municipality_id FROM municipalities WHERE municipality_name = 'Cabuyao')),
    ('Bagong Kalsada', (SELECT municipality_id FROM municipalities WHERE municipality_name = 'Santa Rosa')),
    ('Bambang',        (SELECT municipality_id FROM municipalities WHERE municipality_name = 'Los Baños'));

-- ---- Sample predictions (CNN-LSTM output) for Wet 2024 ----
INSERT INTO predictions (predicted_yield, barangay_id, season_id) VALUES
    (5.10, (SELECT barangay_id FROM barangays WHERE barangay_name = 'San Isidro'),
           (SELECT season_id FROM seasons WHERE season_type = 'Wet' AND year = 2024)),
    (4.80, (SELECT barangay_id FROM barangays WHERE barangay_name = 'Mamatid'),
           (SELECT season_id FROM seasons WHERE season_type = 'Wet' AND year = 2024)),
    (4.30, (SELECT barangay_id FROM barangays WHERE barangay_name = 'Bambang'),
           (SELECT season_id FROM seasons WHERE season_type = 'Wet' AND year = 2024));

-- ---- Matching observed yields for the same barangay/season ----
INSERT INTO yield_records (observed_yield, barangay_id, season_id) VALUES
    (5.35, (SELECT barangay_id FROM barangays WHERE barangay_name = 'San Isidro'),
           (SELECT season_id FROM seasons WHERE season_type = 'Wet' AND year = 2024)),
    (4.60, (SELECT barangay_id FROM barangays WHERE barangay_name = 'Mamatid'),
           (SELECT season_id FROM seasons WHERE season_type = 'Wet' AND year = 2024)),
    (4.45, (SELECT barangay_id FROM barangays WHERE barangay_name = 'Bambang'),
           (SELECT season_id FROM seasons WHERE season_type = 'Wet' AND year = 2024));

-- ---- Residuals (observed - predicted), pairing each prediction with its actual ----
INSERT INTO residuals (residual_value, prediction_id, yield_id)
SELECT
    y.observed_yield - p.predicted_yield,
    p.prediction_id,
    y.yield_id
FROM predictions p
JOIN yield_records y
     ON y.barangay_id = p.barangay_id
    AND y.season_id   = p.season_id;
